version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/client"
      - "/server"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
